#!/usr/bin/env node
'use strict';
const ActivityLog = require('../server/models/ActivityLog');
const Document = require('../server/models/Document');
const Promise = require('bluebird');
const User = require('../server/models/User');

let models = [ActivityLog, Document, User];


function done() {
  process.exit(0);
}

function error(err) {
  console.error(err);
  process.exit(1);
}

function truncateTable(model) {
  return model.destroy({ truncate: true });
}

Promise.map(models, truncateTable)
  .then(done)
  .catch(error);
